export const TEMPLATES = [
  {
    templateName: "Sidenav",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "TNS",

    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S0",
    floatingMenu: "FALSE",
    logoBgColor: "#171725",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT2",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "XXXL",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "XXXL",
    logoheightsize: "XS",
  },
  {
    templateName: "Sidenav : (S-LN)",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",

    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S1",
    floatingMenu: "FALSE",

    logoBgColor: "#1e1e2f",
    topnavBgColor: "#1e1e2f",
    sidenavBgColor: "#ffffff",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "S",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "S",
    logoheightsize: "XS",
  },

  {
    templateName: "Sidenav : (P)(S-LN)",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",

    gridConfig: "S1",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "SLN",
    template: "S1",
    floatingMenu: "FALSE",

    logoBgColor: "#171725",
    topnavBgColor: "#1e1e2f",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "L",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "L",
    logoheightsize: "XS",
  },
  {
    templateName: "Sidenav : (P)(S-L-N)",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",

    gridConfig: "S2",
    rounded: "SLN",
    boxed: "SLN",
    padded: "SLN",
    template: "S2",
    floatingMenu: "FALSE",

    logoBgColor: "#ffffff",
    topnavBgColor: "#ffffff",
    sidenavBgColor: "#ffffff",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "XS",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "XS",
    logoheightsize: "XS",
  },
  {
    templateName: "Sidenav : (P)(SL-N)",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",

    gridConfig: "S0",
    rounded: "SL_N",
    boxed: "SL_N",
    padded: "SLN",
    template: "S0",
    floatingMenu: "FALSE",

    logoBgColor: "#171725",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "XXXL",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "XXXL",
    logoheightsize: "XS",
  },

  {
    templateName: "Sidenav Compact Floating",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",

    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "FALSE",
    template: "S2",
    sidenavMenuAlignCenter: "FALSE",
    topnavSecondaryBgColor: "NA",
    logoBgColor: "transparent",
    topnavBgColor: "transparent",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "XXXS",
    appBgColor: "#171725",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "S",
    logoheightsize: "XS",
  },
  {
    templateName: "Sidenav Compact Floating : (P)(S-LN)",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",

    gridConfig: "S2",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S2",
    sidenavMenuAlignCenter: "FALSE",
    topnavSecondaryBgColor: "NA",
    logoBgColor: "transparent",
    topnavBgColor: "transparent",
    sidenavBgColor: "#007bff",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "M",
    appBgColor: "#171725",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "M",
    logoheightsize: "XS",
  },
  {
    templateName: "Sidenav Compact Floating : (P)(S-L-N)",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",

    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "SLN",
    template: "S2",
    sidenavMenuAlignCenter: "FALSE",
    topnavSecondaryBgColor: "NA",
    logoBgColor: "#1e1e2f",
    topnavBgColor: "#171725",
    sidenavBgColor: "#ffffff",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "XXS",
    appBgColor: "#f2f2f2",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "L",
    logoheightsize: "XS",
  },

  //topnavigation
  {
    templateName: "Topnav Standard",
    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",

    gridConfig: "N0",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N0",
    floatingMenu: "FALSE",

    logoBgColor: "#1e1e2f",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "NA",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "M",
    logoheightsize: "XS",
  },
  {
    templateName: "Topnav Standard Padded",
    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",

    gridConfig: "N0",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "SLN",
    template: "N0",
    floatingMenu: "FALSE",

    logoBgColor: "#1e1e2f",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "NA",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "NA",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "M",
    logoheightsize: "XS",
  },
  {
    templateName: "Topnav Stacked",

    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",

    gridConfig: "N1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N1",
    floatingMenu: "FALSE",

    logoBgColor: "#1e1e2f",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "NA",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "#02020229",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "FALSE",
    sidenavOnly: "FALSE",
    logowidthsize: "M",
    logoheightsize: "XS",
  },
  {
    templateName: "Topnav Stacked LN",

    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",

    gridConfig: "N1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N1",
    floatingMenu: "FALSE",

    logoBgColor: "#1e1e2f",
    topnavBgColor: "white",
    sidenavBgColor: "#1e1e2f",
    sidenavlinktemplate: "SLT1",
    topnavlinktemplate: "LT1_NOICON",
    topnavsize: "XS",
    sidenavsize: "NA",
    appBgColor: "#f2f2f2",
    topnavSecondaryBgColor: "#02020229",
    sidenavMenuAlignCenter: "FALSE",
    containerBgColor: null,
    contained: "FALSE",
    tnshadow: "FALSE",
    snshadow: "FALSE",
    logoOnNav: "TRUE",
    sidenavOnly: "FALSE",
    logowidthsize: "M",
    logoheightsize: "XS",
  },
];
