export const TEMPLATES = [
  {
    templateName: "Sidenav Standard",
    templateID: "S0",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "TNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S0",

    logoBgColor: "#171725",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT2",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Reduced",
    templateID: "S1",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S1",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT1",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Compact",
    templateID: "S2",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S2",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT1_ROUNDED",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav (S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S0",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "#1e1e2f",
    sidebarBgColor: "#ffffff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },

  {
    templateName: "Sidenav (P)(S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "SLN",
    template: "S0",

    logoBgColor: "#ffffff",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav (P)(S-L-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "SLN",
    padded: "SLN",
    template: "S0",

    logoBgColor: "#ffffff",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav (P)(SL-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S0",
    rounded: "FALSE",
    boxed: "SL_N",
    padded: "SLN",
    template: "S0",

    logoBgColor: "#171725",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },

  {
    templateName: "Sidenav Reduced (S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S1",

    logoBgColor: "#ffffff",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Reduced (P)(S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "SLN",
    template: "S1",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "#1e1e2f",
    sidebarBgColor: "#ffffff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Reduced (P)(S-L-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "SLN",
    boxed: "SLN",
    padded: "SLN",
    template: "S1",

    logoBgColor: "#ffffff",
    navbarBgColor: "#ffffff",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },

  {
    templateName: "Sidenav Reduced (P)(SL-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "dark",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "SL_N",
    boxed: "SL_N",
    padded: "SLN",
    template: "S1",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },

  {
    templateName: "Sidenav Compact (S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S2",

    logoBgColor: "#171725",
    navbarBgColor: "#1e1e2f",
    sidebarBgColor: "#ffffff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Compact (P)(S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "SLN",
    template: "S2",

    logoBgColor: "#ffffff",
    navbarBgColor: "#ffffff",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Compact (P)(SLN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "SLN",
    boxed: "SLN",
    padded: "SLN",
    template: "S2",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "#1e1e2f",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Compact (P)(SL_N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "SL_N",
    boxed: "SL_N",
    padded: "SLN",
    template: "S2",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    templateName: "Sidenav Compact Floating",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S2",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },
  {
    templateName: "Sidenav Compact Floating (P)(S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S2",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },
  {
    templateName: "Sidenav Compact Floating (P)(S-L-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S2",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "SLN",
    template: "S2",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },

  {
    templateName: "Sidenav Reduced Floating",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "S1",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },
  {
    templateName: "Sidenav Reduced Floating (P)(S-LN)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "S_LN",
    template: "S1",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },
  {
    templateName: "Sidenav Reduced Floating (P)(S-L-N)",
    templateID: "S0B",
    selectedPage: "/admin",

    logoTheme: "light",
    layout: "SIDE_NAVIGATION",
    floatingMenu: "SIDENAV",
    submenuConfig: "SNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "S1",
    rounded: "FALSE",
    boxed: "S_LN",
    padded: "SLN",
    template: "S1",

    logoBgColor: "transparent",
    navbarBgColor: "transparent",
    sidebarBgColor: "#007bff",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#171725",
  },

  //topnavigation
  {
    selectedPage: "/admin",
    templateName: "Topnav Standard",
    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "N0",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N0",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    selectedPage: "/admin",
    templateName: "Topnav Standard Padded",
    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "N0",
    rounded: "S_LN",
    boxed: "S_LN",
    padded: "SLN",
    template: "N0",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "XS",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    selectedPage: "/admin",
    templateName: "Topnav Stacked",

    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "N1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N1",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
  },
  {
    selectedPage: "/admin",
    templateName: "Topnav Stacked LN",

    logoTheme: "dark",
    layout: "TOP_NAVIGATION",
    submenuConfig: "TNS",
    searchbarConfig: {
      placement: "RIGHT",
      width: "15vw",
      floating: true,
      hash: "FR",
    },
    gridConfig: "N1",
    rounded: "FALSE",
    boxed: "FALSE",
    padded: "FALSE",
    template: "N1",

    logoBgColor: "#1e1e2f",
    navbarBgColor: "white",
    sidebarBgColor: "#1e1e2f",
    sidebarlinktemplate: "SLT0",
    navbarlinktemplate: "LT0_NOICON",
    navbarsize: "M",
    sidebarsize: "S",
    appBgColor: "#f2f2f2",
    logoOnNav: "TRUE",
  },
];
